version: '3.1'

services:
  app:
    build: .
    ports: 
    - 8080:8080
    depends_on:
    - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
    - 27017:27017
